apiVersion: apps/v1
kind: Deployment
metadata:
  name: alien-invaders-app-deployment
spec:
  selector:
   matchLabels:
    app: alien-invaders-app
  replicas: 1
  template:
    metadata:
      labels:
        app: alien-invaders-app
    spec:
      containers:
        - name: alien-invaders-app
          image: alejandrorodriguezsalazar/alien-invaders:latest
          imagePullPolicy: Always
          env:
            - name: NODE_SERVER_PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: alien-invaders