apiVersion: v1
kind: Service
metadata:
  name: alien-invaders-app-service
  labels:
    app: alien-invaders-app
spec:
  ports:
  - name: alien-invaders-app
    port: 3000
    nodePort : 30780
  #type: LoadBalancer
  type: NodePort
  selector:
   app: alien-invaders-app